name: Test Python dev branches

on:
  push:
    branches: [ "dev-*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install  flask pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Initialize the test database
        run: |
          python manage.py create dummy
      - name: Test with pytest
        run: |
          python -m pytest
